// You can add your native dependencies here
// dependencies {
//   implementation 'androidx.core:core-ktx:1.15.0'
// }

android {
  compileSdkVersion 36
  buildToolsVersion "36.0.0"
  // ndkVersion ""

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 36

    // Version Information
    versionCode 1
    versionName "1.0.0"
    
    generatedDensities = []
  }

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
